server:
  port: 8088

spring:
  datasource:
    url:  jdbc:mysql://49.235.226.26:3306/foodie-shop-dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    password:  Aa@123123
  redis:
    # redis 单机单实例
    database: 1
    host: 49.235.226.26
    port: 6379
    password: Aa@123123


    # redis 哨兵模式
#    database: 1
#    password: imooc
#    sentinel:
#      master: imooc-master
#      nodes: 192.168.0.1:26379,192.168.0.2:26379,192.168.0.3:26379

    # redis 集群
#    password: imooc
#    cluster:
#      nodes: 192.168.0.1:6379,192.168.0.2:6379,192.168.0.3:6379,192.168.0.4:6379,192.168.0.5:6379,192.168.0.6:6379

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #  mybatis日志