server:
  port: 8088

spring:
  datasource:
    url:  jdbc:mysql://49.235.226.26:3306/hosipital?useUnicode=true&characterEncoding=utf-8&useSSL=false
    password:  Aa@123123
  redis:
    # redis 单机单实例
    database: 1
    host: 49.235.226.26
    port: 6379
    password: Aa@123123

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #  mybatis日志